---
require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - bundle/vendor/**/*
    - vendor/**/*
    - bin/*
    - db/migrate/*
    - db/schema.rb

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - test/**/*

Metrics/AbcSize:
  Max: 20
    
Metrics/CyclomaticComplexity:
  Max: 10

Rails/I18nLocaleTexts:
  Enabled: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 120
