---
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - bundle/vendor/**/*
    - bin/*

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 120
