---
name: CI
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Run rubocop
        run: |
          bin/rubocop --parallel

  sorbet:
    name: Sorbet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Run rubocop
        run: |
          bin/srb tc

  spoom_bump:
    name: Ensure type sigils are bumped
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Bump from false to true
        run: |
          bin/spoom bump --dry --from false --to true
      - name: Bump from true to strict
        run: |
          bin/spoom bump --dry --from true --to strict
          
  tapioca_dsl:
    name: Ensure tapioca dsls are up-to-date
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run dependencies
        uses: isbang/compose-action@v1.4.1


      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile
          
      - name: Setup database
        run: |
          bin/rails db:setup

      - name: Run tapioca dsl
        run: |
          bin/tapioca dsl --verify
          
  tapioca_gem:
    name: Ensure tapioca gem definitions are up-to-date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Run tapioca gem
        run: |
          bin/tapioca gem --verify
          
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run dependencies
        uses: isbang/compose-action@v1.4.1

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Build assets
        run: |
          yarn build
          yarn build:css

      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:setup
          
      - name: Run tests
        run: bin/rails test
          
  system_tests:
    name: System tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run dependencies
        uses: isbang/compose-action@v1.4.1

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:setup
          
      - name: Run tests
        run: bin/rails test:system
        
  deploy:
    runs-on: ubuntu-latest
    needs:
      - rubocop
      - sorbet
      - spoom_bump
      - system_tests
      - tapioca_dsl
      - tapioca_gem
      - tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: main
          git_remote_url: ${{ secrets.DOKKU_HOST }}
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
